branches:
  prod:
    enforce_admins: true
    required_status_checks:
      strict: true
      contexts:
        - "CodeQL"
        - "Copilot Autofix"
    required_pull_request_reviews:
      dismiss_stale_reviews: true
      require_code_owner_reviews: true
      required_approving_review_count: 1
      require_last_push_approval: true
    required_linear_history: true
    allow_force_pushes: false
    allow_deletions: false
    block_creations: true
    required_conversation_resolution: true
    required_signatures: true

  test:
    enforce_admins: false
    required_status_checks:
      strict: true
      contexts:
        - "CodeQL"
        - "Copilot Autofix"
    required_pull_request_reviews:
      require_code_owner_reviews: false
      required_approving_review_count: 0
    allow_force_pushes: false