name: Enforce Branch Protection Rules

on:
  push:
    branches:
      - prod
      - test
    paths:
      - '.github/branch-protection.yml'
  workflow_dispatch:

jobs:
  enforce-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Enforce branch protection (prod)
        env:
          GH_TOKEN: ${{ secrets.GH_ADMIN_TOKEN }}  # PAT with admin rights
        run: |
          gh --version
          gh api \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/branches/prod/protection \
            -f required_status_checks='{"strict":true,"contexts":["CodeQL"]}' \
            -f enforce_admins=true \
            -f required_pull_request_reviews='{"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":1}' \
            -f restrictions=null \
            -f required_linear_history=true \
            -f allow_force_pushes=false \
            -f allow_deletions=false
